onlyBuiltDependencies:
  - '@astrojs/compiler'
  - '@astrojs/internal-helpers'
  - '@astrojs/markdown-remark'
  - '@astrojs/mdx'
  - '@astrojs/prism'
  - '@astrojs/sitemap'
  - '@astrojs/starlight'
  - '@astrojs/telemetry'
  - '@babel/helper-string-parser'
  - '@babel/helper-validator-identifier'
  - '@babel/parser'
  - '@babel/runtime'
  - '@babel/types'
  - '@capsizecss/unpack'
  - '@ctrl/tinycolor'
  - '@esbuild/darwin-arm64'
  - '@expressive-code/core'
  - '@expressive-code/plugin-frames'
  - '@expressive-code/plugin-shiki'
  - '@expressive-code/plugin-text-markers'
  - '@img/sharp-darwin-arm64'
  - '@img/sharp-libvips-darwin-arm64'
  - '@jridgewell/sourcemap-codec'
  - '@mdx-js/mdx'
  - '@oslojs/encoding'
  - '@pagefind/darwin-arm64'
  - '@pagefind/default-ui'
  - '@rollup/pluginutils'
  - '@rollup/rollup-darwin-arm64'
  - '@shikijs/core'
  - '@shikijs/engine-javascript'
  - '@shikijs/engine-oniguruma'
  - '@shikijs/langs'
  - '@shikijs/themes'
  - '@shikijs/types'
  - '@shikijs/vscode-textmate'
  - '@swc/helpers'
  - '@types/debug'
  - '@types/estree'
  - '@types/estree-jsx'
  - '@types/hast'
  - '@types/js-yaml'
  - '@types/mdast'
  - '@types/mdx'
  - '@types/ms'
  - '@types/nlcst'
  - '@types/node'
  - '@types/sax'
  - '@types/unist'
  - '@ungap/structured-clone'
  - acorn
  - acorn-jsx
  - ansi-align
  - ansi-regex
  - ansi-styles
  - anymatch
  - arg
  - argparse
  - aria-query
  - array-iterate
  - astring
  - astro
  - astro-expressive-code
  - axobject-query
  - bail
  - base-64
  - base64-js
  - bcp-47
  - bcp-47-match
  - blob-to-buffer
  - boolbase
  - boxen
  - brotli
  - camelcase
  - ccount
  - chalk
  - character-entities
  - character-entities-html4
  - character-entities-legacy
  - character-reference-invalid
  - chokidar
  - ci-info
  - cli-boxes
  - clone
  - clsx
  - collapse-white-space
  - color
  - color-convert
  - color-name
  - color-string
  - comma-separated-tokens
  - common-ancestor-path
  - cookie
  - cookie-es
  - cross-fetch
  - crossws
  - css-selector-parser
  - css-tree
  - cssesc
  - debug
  - decode-named-character-reference
  - defu
  - dequal
  - destr
  - detect-libc
  - deterministic-object-hash
  - devalue
  - devlop
  - dfa
  - diff
  - direction
  - dlv
  - dset
  - emoji-regex
  - emoji-regex-xs
  - entities
  - es-module-lexer
  - esast-util-from-estree
  - esast-util-from-js
  - esbuild
  - escape-string-regexp
  - estree-util-attach-comments
  - estree-util-build-jsx
  - estree-util-is-identifier-name
  - estree-util-scope
  - estree-util-to-js
  - estree-util-visit
  - estree-walker
  - eventemitter3
  - expressive-code
  - extend
  - fast-deep-equal
  - fdir
  - flattie
  - fontkit
  - fsevents
  - get-east-asian-width
  - github-slugger
  - h3
  - hast-util-embedded
  - hast-util-format
  - hast-util-from-html
  - hast-util-from-parse5
  - hast-util-has-property
  - hast-util-is-body-ok-link
  - hast-util-is-element
  - hast-util-minify-whitespace
  - hast-util-parse-selector
  - hast-util-phrasing
  - hast-util-raw
  - hast-util-select
  - hast-util-to-estree
  - hast-util-to-html
  - hast-util-to-jsx-runtime
  - hast-util-to-parse5
  - hast-util-to-string
  - hast-util-to-text
  - hast-util-whitespace
  - hastscript
  - html-escaper
  - html-void-elements
  - html-whitespace-sensitive-tag-names
  - http-cache-semantics
  - i18next
  - import-meta-resolve
  - inline-style-parser
  - iron-webcrypto
  - is-alphabetical
  - is-alphanumerical
  - is-arrayish
  - is-decimal
  - is-docker
  - is-fullwidth-code-point
  - is-hexadecimal
  - is-inside-container
  - is-plain-obj
  - is-wsl
  - js-yaml
  - kleur
  - klona
  - longest-streak
  - lru-cache
  - magic-string
  - magicast
  - markdown-extensions
  - markdown-table
  - mdast-util-definitions
  - mdast-util-directive
  - mdast-util-find-and-replace
  - mdast-util-from-markdown
  - mdast-util-gfm
  - mdast-util-gfm-autolink-literal
  - mdast-util-gfm-footnote
  - mdast-util-gfm-strikethrough
  - mdast-util-gfm-table
  - mdast-util-gfm-task-list-item
  - mdast-util-mdx
  - mdast-util-mdx-expression
  - mdast-util-mdx-jsx
  - mdast-util-mdxjs-esm
  - mdast-util-phrasing
  - mdast-util-to-hast
  - mdast-util-to-markdown
  - mdast-util-to-string
  - mdn-data
  - micromark
  - micromark-core-commonmark
  - micromark-extension-directive
  - micromark-extension-gfm
  - micromark-extension-gfm-autolink-literal
  - micromark-extension-gfm-footnote
  - micromark-extension-gfm-strikethrough
  - micromark-extension-gfm-table
  - micromark-extension-gfm-tagfilter
  - micromark-extension-gfm-task-list-item
  - micromark-extension-mdx-expression
  - micromark-extension-mdx-jsx
  - micromark-extension-mdx-md
  - micromark-extension-mdxjs
  - micromark-extension-mdxjs-esm
  - micromark-factory-destination
  - micromark-factory-label
  - micromark-factory-mdx-expression
  - micromark-factory-space
  - micromark-factory-title
  - micromark-factory-whitespace
  - micromark-util-character
  - micromark-util-chunked
  - micromark-util-classify-character
  - micromark-util-combine-extensions
  - micromark-util-decode-numeric-character-reference
  - micromark-util-decode-string
  - micromark-util-encode
  - micromark-util-events-to-acorn
  - micromark-util-html-tag-name
  - micromark-util-normalize-identifier
  - micromark-util-resolve-all
  - micromark-util-sanitize-uri
  - micromark-util-subtokenize
  - micromark-util-symbol
  - micromark-util-types
  - mrmime
  - ms
  - nanoid
  - neotraverse
  - nlcst-to-string
  - node-fetch
  - node-fetch-native
  - node-mock-http
  - normalize-path
  - nth-check
  - ofetch
  - ohash
  - oniguruma-parser
  - oniguruma-to-es
  - p-limit
  - p-queue
  - p-timeout
  - package-manager-detector
  - pagefind
  - pako
  - parse-entities
  - parse-latin
  - parse5
  - picocolors
  - picomatch
  - postcss
  - postcss-nested
  - postcss-selector-parser
  - prismjs
  - prompts
  - property-information
  - radix3
  - readdirp
  - recma-build-jsx
  - recma-jsx
  - recma-parse
  - recma-stringify
  - regenerator-runtime
  - regex
  - regex-recursion
  - regex-utilities
  - rehype
  - rehype-expressive-code
  - rehype-format
  - rehype-parse
  - rehype-raw
  - rehype-recma
  - rehype-stringify
  - remark-directive
  - remark-gfm
  - remark-mdx
  - remark-parse
  - remark-rehype
  - remark-smartypants
  - remark-stringify
  - restructure
  - retext
  - retext-latin
  - retext-smartypants
  - retext-stringify
  - rollup
  - sax
  - semver
  - sharp
  - shiki
  - simple-swizzle
  - sisteransi
  - sitemap
  - smol-toml
  - source-map
  - source-map-js
  - space-separated-tokens
  - stream-replace-string
  - string-width
  - stringify-entities
  - strip-ansi
  - style-to-js
  - style-to-object
  - tiny-inflate
  - tinyexec
  - tinyglobby
  - tr46
  - trim-lines
  - trough
  - tsconfck
  - tslib
  - type-fest
  - typescript
  - ufo
  - ultrahtml
  - uncrypto
  - unicode-properties
  - unicode-trie
  - unified
  - unifont
  - unist-util-find-after
  - unist-util-is
  - unist-util-modify-children
  - unist-util-position
  - unist-util-position-from-estree
  - unist-util-remove-position
  - unist-util-stringify-position
  - unist-util-visit
  - unist-util-visit-children
  - unist-util-visit-parents
  - unstorage
  - util-deprecate
  - vfile
  - vfile-location
  - vfile-message
  - vite
  - vitefu
  - web-namespaces
  - webidl-conversions
  - whatwg-url
  - which-pm-runs
  - widest-line
  - wrap-ansi
  - xxhash-wasm
  - yargs-parser
  - yocto-queue
  - yocto-spinner
  - yoctocolors
  - zod
  - zod-to-json-schema
  - zod-to-ts
  - zwitch
