name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SURGE_TOKEN secret exists
        id: check_token
        run: |
          if [[ -n "${{ secrets.SURGE_TOKEN }}" ]]; then
            echo "token_exists=true" >> $GITHUB_OUTPUT
          else
            echo "token_exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ WARNING: SURGE_TOKEN is not set in the repository secrets."
            echo "Please add it in your repository settings under Secrets > Actions."
            echo "You can get a token by running 'npx surge token' locally."
          fi
      
      - name: Setup Surge
        if: steps.check_token.outputs.token_exists == 'true'
        run: |
          npm install -g surge
          mkdir -p ~/.surge
          echo "${{ secrets.SURGE_TOKEN }}" > ~/.surge/token
          
      - name: Delete Surge.sh Preview
        if: steps.check_token.outputs.token_exists == 'true'
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/.*\///')
          DEPLOY_DOMAIN="pr-${{ github.event.pull_request.number }}-${REPO_NAME}.surge.sh"
          surge teardown $DEPLOY_DOMAIN
          
      - name: Comment PR Success
        if: steps.check_token.outputs.token_exists == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🗑️ Preview deployment has been removed as this PR was closed.'
            })
            
      - name: Comment PR with Token Missing Warning
        if: steps.check_token.outputs.token_exists == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `⚠️ **No se pudo eliminar el despliegue de preview**

            El secreto SURGE_TOKEN no está configurado en este repositorio.
            
            Para configurarlo:
            1. Genera un token con \`npx surge token\` en tu máquina local
            2. Ve a Settings > Secrets and variables > Actions en este repositorio
            3. Crea un nuevo secreto llamado SURGE_TOKEN con el valor generado`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
