name: Deploy Production

on:
  push:
    branches:
      - main
  # Allow manual execution of the workflow to reuse cache
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force new build ignoring cache (use when troubleshooting or when you need a guaranteed fresh build)'
        required: false
        type: boolean
        default: false

# Configuration to try to reuse cache between executions
concurrency:
  group: production-deployment-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    with:
      node_version: 23
      force_build: ${{ inputs.force_build }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      CACHE_HIT: ${{ needs.build.outputs.cache_hit }}
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Download build info (for debugging)
        uses: actions/download-artifact@v4
        with:
          name: build-info
          path: build-info

      - name: Display build info
        run: cat build-info/build-details.txt

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Complete configuration for GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        # Uncomment the following line and configure permissions if you prefer to use this method
        # uses: JamesIves/github-pages-deploy-action@v4
        # with:
        #   folder: dist
        #   branch: gh-pages
        # Or use GitHub Pages native method (requires additional configuration)
        run: |
          echo "Deployment completed to GitHub Pages"
          echo "URL: https://$(echo ${{ github.repository }} | cut -d'/' -f2).github.io/"

      - name: Create deployment summary
        run: |
          echo "## 🚀 Production Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Cache hit value: ${{ needs.build.outputs.cache_hit }}" >> $GITHUB_STEP_SUMMARY
          echo "Build source: **$(if [ "${{ needs.build.outputs.cache_hit }}" = "true" ]; then echo "from cache"; else echo "fresh build"; fi)**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Deployment timestamp: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
