name: PR Preview with Surge.sh

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-preview:
    # Don't run this job if the PR is closed AND the event is "closed"
    if: github.event.action != 'closed'
    uses: ./.github/workflows/shared-build.yml
    with:
      deploy_to_surge: true
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}

  comment-on-pr:
    needs: deploy-preview
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Use the URL directly from the reusable workflow
            const previewUrl = '${{ needs.deploy-preview.outputs.preview_url }}';

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Preview Deployed

              Your PR is now available for review at: [${previewUrl}](${previewUrl})

              This URL will remain active until the PR is closed or merged.`
            });

  cleanup-preview:
    runs-on: ubuntu-latest
    # Only run this job when the PR is closed
    if: github.event.action == 'closed'

    steps:
      - name: Setup domain name
        id: domain
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "value=pr-${PR_NUMBER}-${REPO_NAME}.surge.sh" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js with PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Surge with PNPM
        run: pnpm add --global surge

      - name: Teardown Surge deployment
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        run: |
          # Use the domain defined in the previous step
          DOMAIN="${{ steps.domain.outputs.value }}"
          echo "Removing deployment at $DOMAIN..."
          echo "Using user $SURGE_LOGIN"

          # Use pnpm to execute surge
          pnpm exec surge teardown "$DOMAIN" --token "$SURGE_TOKEN"

      - name: Comment PR Cleanup
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const domain = '${{ steps.domain.outputs.value }}';
            const previewUrl = `https://${domain}`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🧹 Preview Removed

              The preview at \`${previewUrl}\` has been removed since the PR has been ${context.payload.pull_request.merged ? 'merged' : 'closed'}.`
            });
