name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      has_token: ${{ steps.check_token.outputs.has_token }}
    steps:
      - name: Debug secrets
        run: |
          echo "Checking available secrets and context..."
          echo "Has SURGE_TOKEN? ${{ secrets.SURGE_TOKEN != '' }}"
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
      
      - name: Check for SURGE_TOKEN
        id: check_token
        run: |
          if [ -n "${{ secrets.SURGE_TOKEN }}" ]; then
            echo "has_token=true" >> $GITHUB_OUTPUT
          else
            echo "has_token=false" >> $GITHUB_OUTPUT
          fi

  fail-if-no-token:
    needs: check-secrets
    if: needs.check-secrets.outputs.has_token == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Fail workflow
        run: |
          echo "::error::SURGE_TOKEN is not set in the repository secrets or is empty."
          echo "Please add it in your repository settings under Settings > Secrets and variables > Actions."
          echo "You can get a token by running 'npx surge token' locally."
          exit 1

  deploy-preview:
    needs: check-secrets
    if: needs.check-secrets.outputs.has_token == 'true'
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '23'
      REPO_NAME: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        
      - name: Setup Surge
        run: |
          pnpm install -g surge
          mkdir -p ~/.surge
          echo "${{ secrets.SURGE_TOKEN }}" > ~/.surge/token

      - name: Generate domain name
        id: domain
        run: |
          generate_domain() {
            local repo_name=$(echo "$REPO_NAME" | sed 's/.*\///')
            echo "pr-$PR_NUMBER-${repo_name}.surge.sh"
          }
          
          DEPLOY_DOMAIN=$(generate_domain)
          echo "deploy_domain=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT
          echo "url=https://$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - name: Deploy to Surge
        run: |
          TOKEN=${{ secrets.SURGE_TOKEN }} surge ./dist ${{ steps.domain.outputs.deploy_domain }} --token $TOKEN

      - name: Comment PR with Deployment URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `🚀 Preview deployment is ready!

            URL: ${{ steps.domain.outputs.url }}

            Built with Node.js ${{ env.NODE_VERSION }} and pnpm`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
