name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '23'
      REPO_NAME: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Check if SURGE_TOKEN secret exists
        run: |
          if [[ -z "${{ secrets.SURGE_TOKEN }}" ]]; then
            echo "::error::SURGE_TOKEN is not set in the repository secrets."
            echo "Please add it in your repository settings under Secrets > Actions."
            echo "You can get a token by running 'npx surge token' locally."
            exit 1
          fi
          echo "Surge token is configured correctly."

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Setup Surge
        run: |
          npm install -g surge
          mkdir -p ~/.surge
          echo "${{ secrets.SURGE_TOKEN }}" > ~/.surge/token

      - name: Generate domain name
        id: domain
        run: |
          generate_domain() {
            local repo_name=$(echo "$REPO_NAME" | sed 's/.*\///')
            echo "pr-$PR_NUMBER-${repo_name}.surge.sh"
          }
          
          DEPLOY_DOMAIN=$(generate_domain)
          echo "deploy_domain=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT
          echo "url=https://$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - name: Deploy to Surge
        run: |
          surge ./dist ${{ steps.domain.outputs.deploy_domain }}

      - name: Comment PR with Deployment URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `🚀 Preview deployment is ready!

            URL: ${{ steps.domain.outputs.url }}

            Built with Node.js ${{ env.NODE_VERSION }} and npm`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
