name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to Surge
        id: deploy
        run: |
          pnpm install -g surge
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/.*\///')
          DEPLOY_DOMAIN="pr-${{ github.event.pull_request.number }}-${REPO_NAME}.surge.sh"
          surge ./dist $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
          echo "url=https://$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT
          echo "domain=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `🚀 Preview deployment is ready!

            URL: ${{ steps.deploy.outputs.url }}

            Built with Node.js 20.11.1 and pnpm`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
