name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Setup Surge
        run: |
          npm install -g surge
          mkdir -p ~/.surge
          echo "${{ secrets.SURGE_TOKEN }}" > ~/.surge/token
          
      - name: Verify Surge Token
        run: |
          if [ -z "${{ secrets.SURGE_TOKEN }}" ]; then
            echo "Error: SURGE_TOKEN is not set in the repository secrets."
            exit 1
          fi
          echo "Surge token is configured."

      - name: Deploy to Surge
        id: deploy
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/.*\///')
          DEPLOY_DOMAIN="pr-${{ github.event.pull_request.number }}-${REPO_NAME}.surge.sh"
          surge ./dist $DEPLOY_DOMAIN
          echo "url=https://$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT
          echo "domain=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `🚀 Preview deployment is ready!

            URL: ${{ steps.deploy.outputs.url }}

            Built with Node.js 23 and npm`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
