name: Shared Build Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '23'
      force_build:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 1
          compression-level: 9 # Maximum compression to reduce size

      - name: Save build info
        run: |
          mkdir -p build-info
          echo "Build timestamp: $(date)" > build-info/build-details.txt
          echo "Git commit: ${{ github.sha }}" >> build-info/build-details.txt
          echo "Branch/ref: ${{ github.ref_name }}" >> build-info/build-details.txt
          echo "Node version: ${{ inputs.node_version }}" >> build-info/build-details.txt
          echo "Event: ${{ github.event_name }}" >> build-info/build-details.txt

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info/
          retention-days: 1
