name: Shared Build Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '23'
    outputs:
      cache_hit:
        description: "Indicates if there was a cache hit on the build"
        value: ${{ jobs.build.outputs.cache_hit }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache_hit: ${{ steps.build_cache.outputs.cache-hit }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Cache .vite
        uses: actions/cache@v4
        with:
          path: node_modules/.vite
          key: ${{ runner.os }}-vite-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('astro.config.mjs', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-vite-${{ hashFiles('pnpm-lock.yaml') }}-
            ${{ runner.os }}-vite-

      - name: Check build cache
        id: build_cache
        uses: actions/cache@v4
        with:
          path: |
            dist/
            .astro/
          key: astro-build-${{ hashFiles('src/**/*.{js,jsx,ts,tsx,astro,md,mdx,css,sass,scss}') }}
          restore-keys: |
            astro-build-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        if: steps.build_cache.outputs.cache-hit != 'true'
        run: pnpm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 1
          compression-level: 9

      - name: Save build info
        run: |
          mkdir -p build-info
          echo "Build timestamp: $(date)" > build-info/build-details.txt
          echo "Git commit: ${{ github.sha }}" >> build-info/build-details.txt
          echo "Cache hit: ${{ steps.build_cache.outputs.cache-hit }}" >> build-info/build-details.txt
          echo "Node version: ${{ inputs.node_version }}" >> build-info/build-details.txt
          echo "Files changed: ${{ toJSON(github.event.commits.*.modified) }}" >> build-info/build-details.txt

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info/
          retention-days: 1
